### ISSUE TITLE
塩基配列の中のA,G,C,Tのそれぞれの割合を求める。GC含量wo

### ISSUE THREAD

**Issue by yuki-kimoto** [yuki-kimoto/perlzemibio#3]

**Comment by yuki-kimoto** [comment]
塩基配列の中のA,G,C,Tのそれぞれの割合を求める。GC含量を求める。

https://ja.wikipedia.org/wiki/GC%E5%90%AB%E9%87%8F

・Perlの見出し、説明、使い方、サンプル
・SPVMの見出し、説明、使い方、サンプル
・PerlとSPVMの両方のサンプル。
・Perlの方法が最初、SPVMが後

**Comment by yuki-kimoto** [comment]
次のテーマを、書いても大丈夫でしょうか?

**Comment by motxx** [comment]
はい、大丈夫です
