### ISSUE TITLE
塩基配列を逆相補鎖に変換する

### ISSUE THREAD

**Issue by yuki-kimoto** [yuki-kimoto/perlzemibio#5]
塩基配列を逆相補鎖に変換する

参考
http://revertra.webcrow.jp/DNA/index.php

5'側が先頭と考えてみてください。

・Perl - タイトル、デスクリプション、サンプル
・SPVM - タイトル、デスクリプション、サンプル
・PerlからSPVM呼び出し - タイトル、デスクリプション、サンプル

**Comment by yuki-kimoto** [comment]
ありがとう。

1点だけ。

コードを、パフォーマンスに対して、最適化したいという希望があります。

・ハッシュを使うと、コストがかかるので、ハッシュを使わずに、if文で

**Comment by motxx** [comment]
https://github.com/yuki-kimoto/perlzemibio/issues/5#issuecomment-599861133 こちら対応しました。

**Comment by yuki-kimoto** [comment]
ばっちり。
